//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreAZ.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorEntity> AuthorEntities { get; set; }
        public virtual DbSet<BookEntity> BookEntities { get; set; }
        public virtual DbSet<CategoryEntity> CategoryEntities { get; set; }
        public virtual DbSet<OrderDetailEntity> OrderDetailEntities { get; set; }
        public virtual DbSet<OrderEntity> OrderEntities { get; set; }
        public virtual DbSet<PaymentMethodEntity> PaymentMethodEntities { get; set; }
        public virtual DbSet<PublisherEntity> PublisherEntities { get; set; }
        public virtual DbSet<RoleEntity> RoleEntities { get; set; }
        public virtual DbSet<UserEntity> UserEntities { get; set; }
    }
}
