//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreAZ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderEntity()
        {
            this.OrderDetails = new HashSet<OrderDetailEntity>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerNote { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public long Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailEntity> OrderDetails { get; set; }
        public virtual PaymentMethodEntity PaymentMethod { get; set; }
        public virtual UserEntity User { get; set; }
    }
}
