//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreAZ.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailEntity
    {
        public int ID { get; set; }
        public int BookID { get; set; }
        public System.Guid OrderID { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public long SubTotal { get; set; }
    
        public virtual BookEntity Book { get; set; }
        public virtual OrderEntity Order { get; set; }
    }
}
